name: snap publish release

on:
  push:
    tags:
      - "v*"

jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
          - armhf

    steps:
      - uses: actions/checkout@v5

      - name: build snap
        uses: infinityofspace/snapcraft-multiarch-action@v2.0.0
        id: build
        with:
          architecture: ${{ matrix.platform }}

      - name: publish stable
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable

      - name: publish candidate
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: candidate
